#!/bin/bash
#Menu Section
echo -e ""
echo -e "+ -- --=[ World is Open Source ]=-- -- +" | lolcat

echo -e ""
echo -e ""
echo -e "Menu"
echo -e "===="
echo -e ""
echo -e "   Command            Description"
echo -e "   -------            -----------"
echo -e "   menu               Display all available commands"
echo -e "   usernew            Create New Account"
echo -e "   trial              Create 24hours Trial Account"
echo -e "   delete             Terminate account access"
echo -e "   check              Check account login"
echo -e "   member             List all member"
echo -e "   restart            Restart dropbear, webmin, squid3, OpenVPN and SSH Service"
echo -e "   reboot             Reboot virtual server"
echo -e "   speedtest          Perform server bandwidth speedtest"
echo -e "   info               System Information"
echo -e "   about              Autoscript information"
echo -e "   exit               Exit remote server connection"
echo -e ""
echo -e "Feel Free to contribute and suggest new features for the script"
echo -e "https://github.com/KleKlai/VPS-OpenVPN-Autoscriptt"
